version: '2'
services:
  mysql:
    container_name: mysql
    restart: always
    build: ./data/mysql/
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: my_app
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: my_app
      TZ: "Asia/Tokyo"
  nginx:
    container_name: nginx
    restart: always
    build: ./data/nginx/
    ports:
      - "80:80"
    volumes:
      - "./data/htdocs:/var/www/html"
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - phpfpm
    links:
      - phpfpm
  phpfpm:
    container_name: phpfpm
    restart: always
    build: ./data/phpfpm/
    ports:
      - "9000:9000"
    environment:
      TZ: "Asia/Tokyo"
      ORACLE_HOME: /opt/oracle
      LD_LIBRARY_PATH: /opt/oracle/lib
    volumes:
      - "./data/htdocs:/var/www/html"
    depends_on:
      - mysql
    links:
      - mysql
